spring.datasource.url=jdbc:postgresql://localhost:5432/tracker_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.ru.nsu.naboka.timetracker.mapper=DEBUG
mybatis.configuration.map-underscore-to-camel-case=true